version: "3.8"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    stdin_open: true
  server:
    build: ./server
    ports:
      - "4000:4000"
  rabbitmq:
    build: ./rabbitmq
    ports:
      - 5672:5672
      - 15674:15674
      - 15672:15672

