# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Result',
        ),
    ]
