# Generated by Django 3.1.2 on 2020-10-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201015_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='name',
            new_name='alert_rating',
        ),
    ]
